New .travis.yml for container-based infrastructure
Update `.travis.yml` to utilize Travis CI's newer container-based
infrastructure.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,66 +1,79 @@
-sudo: required
+# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
+language: c
+sudo: false
 
-env:
-    - CABALVER=1.18 GHCVER=7.8.1
-    - CABALVER=1.18 GHCVER=7.8.2
-    - CABALVER=1.18 GHCVER=7.8.3
-    - CABALVER=1.18 GHCVER=7.8.4
-    - CABALVER=1.22 GHCVER=7.10.1
-    - CABALVER=1.22 GHCVER=7.10.2
-    - CABALVER=head GHCVER=head
-    - STACK=STACK
+cache:
+  directories:
+    - $HOME/.cabsnap
+    - $HOME/.cabal/packages
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
 
 matrix:
-    allow_failures:
-        - env: CABALVER=head GHCVER=head
+  include:
+    - env: CABALVER=1.18 GHCVER=7.8.4
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.22 GHCVER=7.10.2
+      compiler: ": #GHC 7.10.2"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}
+
+before_install:
+ - unset CC
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 
 install:
-    - sudo apt-get update
-    - if [ -n "$STACK" ]; then sudo apt-get install libgmp-dev; fi
-    - |
-        set -e
-        if [ -z "$STACK" ]; then
-            sudo add-apt-repository -y ppa:hvr/ghc
-            sudo apt-get update
-            time sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
-            export PATH=/home/travis/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
-            echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
-            cabal update
-        else
-            wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
-            echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main' | sudo tee /etc/apt/sources.list.d/fpco.list
-            sudo apt-get update
-            sudo apt-get install stack -y
-        fi
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+   then
+     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+   fi
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
+ - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
 
+# check whether current requested install-plan matches cached package-db snapshot
+ - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
+   then
+     echo "cabal build-cache HIT";
+     rm -rfv .ghc;
+     cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
+     cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
+   else
+     echo "cabal build-cache MISS";
+     rm -rf $HOME/.cabsnap;
+     mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
+     cabal install --only-dependencies --enable-tests --enable-benchmarks;
+   fi
+
+# snapshot package-db on cache miss
+ - if [ ! -d $HOME/.cabsnap ];
+   then
+      echo "snapshotting package-db to build-cache";
+      mkdir $HOME/.cabsnap;
+      cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
+      cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
+   fi
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-    - |
-        set -e
-        if [ -n "$STACK" ]; then
-            echo -e "\033[0;32mstack setup.\033[0m"
-            sudo stack setup -v
-            echo -e "\033[0;32mstack build.\033[0m"
-            sudo stack build -v
-            echo -e "\033[0;32mstack test.\033[0m"
-            sudo stack test
-        fi
-    - |
-        set -e
-        if [ -z "$STACK" ]; then
-            cabal --version
-            ghc --version
-            echo -e "\033[0;32mcabal install only deps.\033[0m"
-            cabal install --only-dependencies --enable-tests
-            echo -e "\033[0;32mcabal config with tests.\033[0m"
-            cabal configure --enable-tests
-            echo -e "\033[0;32mcabal build.\033[0m"
-            cabal build
-            echo -e "\033[0;32mcabal test.\033[0m"
-            cabal test
-            echo -e "\033[0;32mcabal check.\033[0m"
-            cabal check
-            echo -e "\033[0;32mcabal sdist.\033[0m"
-            cabal sdist
-            echo -e "\033[0;32mcabal install tarball.\033[0m"
-            cabal install --force-reinstalls dist/*-*.tar.gz
-        fi
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal test
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
+
+# Check that the resulting source distribution can be built & installed.
+# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
+# `cabal install --force-reinstalls dist/*-*.tar.gz`
+ - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
+   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
+
+# EOF
